### ISSUE TITLE
View menu items

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/FireHouse-Restaurant-Project#1]
## User story
As a Customer I can view a page that shows the menu so that I can decide what I want to order

___
## Acceptance Criteria:

 - Customer can find the menu on the main page.
 - Customer can view the menu and read it's content.

___
## Tasks:
 - [x] Create menu page
 - [x] Create menu items
 - [x] Create link to menu page on mainpage.
 - [x] Create link to menu page in navbar.
