### ISSUE TITLE
Customer login page

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/FireHouse-Restaurant-Project#3]
## User story
As a Customer I can find the link to login using my credentials so that I can make a booking and find my current bookings.

___
## Acceptance Criteria:

 - As a Customer I can find the link in the navbar to login.
 - As a Customer when logged in I get redirected to the "bookings page" automatically.

___
## Tasks:
 - [x] Create a login page using HTML&CSS with bootstrap.
 - [x] Create the login functionality with allauth.
 - [x] Create the redirect function in views.py
