### ISSUE TITLE
Booking page

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/FireHouse-Restaurant-Project#5]
## User story
As a Customer I can click on a booking page so that I can make my reservation at the restaurant

___
## Acceptance Criteria:

 - Display a booking link on hero section.
 - Display a booking link in the navbar for easy access.
 - Display booking options to Customer, based on guests, date and time.
 - Display a pop-up message to confirm booking.

___
## Tasks:
 - [x] Create the booking link in the hero page
 - [x] Create the booking link in the navbar
 - [x] Create the bookings model
 - [x] Create the views function for the bookings page
 - [x] Create the bookings page HTML & CSS
