### ISSUE TITLE
Manage bookings

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/FireHouse-Restaurant-Project#6]
## User story
As a Customer I can click on  "my booking page" so that I can make changes to my bookings at the restaurant

___
## Acceptance Criteria:

 - Display a my bookings link in the navbar for easy access.
 - Display a list of all the bookings and a link to delete or update the booking.
 - Display a pop-up message to confirm changes.
___
## Tasks:
 - [x] Create the my booking link in the navbar
 - [x] Create the my bookings model
 - [x] Create the views function for the my bookings page
 - [x] Create the my bookings page HTML & CSS
