### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/FireHouse-Restaurant-Project#7]
## User story
As a Owner I can login to an admin panel so that I can view and update current bookings.

___
## Acceptance Criteria:

 - Display a list of all current bookings.
 - Display detailed information about the bookings when clicking on it.
 - Owner can cancel and change bookings upon request.

___
## Tasks:
 - [x] Create the admin panel using the built in django panel
 - [x] Create detailed bookings page in admin panel.
 - [x] Create functionalty to make changes to a booking in the admin panel.
 - [x] Test so that changes to a booking is reflected an the Customer's 'my booking' page.
