### ISSUE TITLE
Admin panel for adding tables and seats

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/FireHouse-Restaurant-Project#8]
## User story
As an Owner I can add tables in the admin panel so that the app can calculate available seats in the restaurant.

___
## Acceptance Criteria:

 - Being able to add a new table
 - Being able to assign how many seats each table will have.

___
## Tasks:
 - [ ] Create a model for adding a table
 - [ ] Register it in the admin panel so it can be accessed by staff
 - [ ] Create a view that adds the table to the database
