### ISSUE TITLE
Admin panel for updating the menu items

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/FireHouse-Restaurant-Project#9]
## User story
As an Owner I can update the menu so that the webpage reflects our current offerings and pricing.

___
## Acceptance Criteria:

 - Being able to create a new item
 - Being able to update an existing item
 - Being able to delete an existing item

___
## Tasks:
 - [ ] Create a new model for the menu items
 - [ ] Register it in the admin panel
 - [ ] Create a view for the model so the database can be updated.
